name: 'transformation'
version: '1.0.0'

profile: 'transformation'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  transformation:
    staging:
      +schema: staging
    marts:
      +schema: marts
    reporting:
      +schema: reporting
